config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index' #se não digitar nada, cai no index direto

  resources :phones
  resources :adrresses
  resources :contacts
  resources :kinds #, :except => [:edit,:destroy]

end

app/controllers/adrresses_controller.rb
class AdrressesController < ApplicationController
  before_action :set_adrress, only: [:show, :edit, :update, :destroy]

  # GET /adrresses
  # GET /adrresses.json
  def index
    @adrresses = Adrress.all.page(params[:page]).per(10)
  end

  # GET /adrresses/1
  # GET /adrresses/1.json
  def show
  end

  # GET /adrresses/new
  def new
    @adrress = Adrress.new
  end

  # GET /adrresses/1/edit
  def edit
  end

  # POST /adrresses
  # POST /adrresses.json
  def create
    @adrress = Adrress.new(adrress_params)

    respond_to do |format|
      if @adrress.save
        format.html { redirect_to @adrress, notice: 'Adrress was successfully created.' }
        format.json { render :show, status: :created, location: @adrress }
      else
        format.html { render :new }
        format.json { render json: @adrress.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adrresses/1
  # PATCH/PUT /adrresses/1.json
  def update
    respond_to do |format|
      if @adrress.update(adrress_params)
        format.html { redirect_to @adrress, notice: 'Adrress was successfully updated.' }
        format.json { render :show, status: :ok, location: @adrress }
      else
        format.html { render :edit }
        format.json { render json: @adrress.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adrresses/1
  # DELETE /adrresses/1.json
  def destroy
    @adrress.destroy
    respond_to do |format|
      format.html { redirect_to adrresses_url, notice: 'Adrress was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adrress
      @adrress = Adrress.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def adrress_params
      params.require(:adrress).permit(:street, :city, :state, :contact_id)
    end
end

app/helpers/adrresses_helper.rb
module AdrressesHelper
end

app/views/adrresses/_form.html.erb
<%= form_for(@adrress, html:{class: "basic-grey"}) do |f| %>
  <% if @adrress.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@adrress.errors.count, "error") %> prohibited this adrress from being saved:</h2>

      <ul>
      <% @adrress.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h1>Endereço</h1>>

  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :contact_id %><br>
    <%= f.text_field :contact_id %>
  </div>
  <div class="actions">
    <%= f.submit "Criar", class: "button" %>
    <%= link_to 'Back', adrresses_path, class: "button-others" %>
  </div>
<% end %>

app/views/adrresses/edit.html.erb
<h1>Editing Adrress</h1>

<%= render 'form' %>

<%= link_to 'Show', @adrress %> |
<%= link_to 'Back', adrresses_path %>

app/views/adrresses/index.html.erb
<div class = "basic-grey">
  <p id="notice"><%= notice %></p>

  <h1><%= "#{t('messages.listing')} #{@adrresses.model.model_name.human(count: @adrresses.count)}" %></h1>

  <table>
    <thead>
      <tr>
        <th><%= Adrress.human_attribute_name("street")%></th>
        <th><%= Adrress.human_attribute_name("city")%></th>
        <th><%= Adrress.human_attribute_name("state")%></th>
        <th><%= "#{t('messages.contact')}"%></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @adrresses.each do |adrress| %>
        <tr style="background: <%=cycle('', 'white')%>">
          <td><%= adrress.street %></td>
          <td><%= adrress.city %></td>
          <td><%= adrress.state %></td>
          <td><%= adrress.contact.name %></td>
          <td><%= link_to t('buttons.show'), adrress %></td>
          <td><%= link_to t('buttons.edit'), edit_adrress_path(adrress) %></td>
          <td><%= link_to t('buttons.destroy'), adrress, method: :delete, data: { confirm: t('messages.confirm') } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<br>
<%= paginate @adrresses %>
  <br>

  <%= link_to t('buttons.new'), new_adrress_path %>
</div>

app/views/adrresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Street:</strong>
  <%= @adrress.street %>
</p>

<p>
  <strong>City:</strong>
  <%= @adrress.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @adrress.state %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @adrress.contact %>
</p>

<%= link_to 'Edit', edit_adrress_path(@adrress) %> |
<%= link_to 'Back', adrresses_path %>